ktor {
  deployment {
    port = ${?KTOR_PORT}
    port = 8081
  }
  application {
    modules = [ com.startspeler.horeca.ApplicationKt.module ]
  }
}

jwt {
  secret = ${?JWT_SECRET}
  issuer = ${?JWT_ISSUER}
  audience = ${?JWT_AUDIENCE}
  expirationMs = 86400000
}